### ISSUE TITLE
Text rendering outside metadata table

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#278] opened 2019-08-09 09:11 UTC
Darri (Iceland): While browsing the website I have noticed a rendering anomaly in some of the metadata tables for SDG indicators (see. e.g. https://sustainabledevelopment-uk.github.io/16-1-1/). In some cases the text in the tables displays outside the table limits.

![image](https://user-images.githubusercontent.com/43404358/62768595-152ef780-ba8f-11e9-8cf5-aae05014bf77.png)

**Comment by brockfanning** [comment] 2019-08-10 22:30
Confirmed - I see the same thing Chrome (though interestingly Firefox doesn't have the problem).

**Comment by brockfanning** [comment] 2019-12-21 20:39
Estimate: This should not be that hard, but unfortunately I'm not seeing an obvious cause. I'd estimate about 5-10 hours due to more investigation. This may involve `table-layout: fixed` in some way.

**Comment by brockfanning** [comment] 2019-12-29 04:13
@LucyGwilliamAdmin After findings in #421 do you think we should close this? Or do we need any documentation added?

**Comment by LucyGwilliamAdmin** [comment] 2020-01-02 09:09
@brockfanning I liked your suggestion of having a warning in the metadata documentation about really long words e.g. raw URLs but other than that I don't think this requires anything else

**Closed** 2020-01-03 17:39 UTC
Labels: 1.0.0, bug, design
