### ISSUE TITLE
NaN values are used for valueRange in maps

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1248] opened 2021-06-25 05:58 UTC
**Please complete the following information** 
Site repository URL: [https://github.com/MoBosse/testSite](https://github.com/MoBosse/testSite)
Open SDG version: 1.4.0-dev

**Describe the bug**
If the csv file of an indicator with map contains a row without a value (I want those years to be displayed in the table) this NaN is included when determining the range of values according to which the colors are assigned on the map.

Example: Here is a map where all map relevant lines in the csv have a value
![grafik](https://user-images.githubusercontent.com/50657629/123375946-f0ac6d80-d589-11eb-93bf-a827fdebd3eb.png)

Now, when I delete only one value (for the state in the south-east), the value range seems to be calculated with a zero as minimal value as the colour of several other states have changed too. Furthermore, the legend in the upper right corner no longer shows a value.

![grafik](https://user-images.githubusercontent.com/50657629/123376245-76c8b400-d58a-11eb-8a56-b8e5b0cd9066.png)

**To Reproduce**
1. Go to [https://mobosse.github.io/testSite/en/1-4-2/](https://mobosse.github.io/testSite/en/1-4-2/)
2. Click on 'map'
3. See the described behaviour

**Expected behavior**
I would expect nan values to be ignored when the range of values is determined

**Comment by brockfanning** [comment] 2021-09-01 15:00
@MoBosse This should be fixed by an open pull-request, #1311, in case you have time to test it out.

**Comment by MoBosse** [comment] 2021-09-02 06:17
@brockfanning works perfectly. Thanks!

**Comment by brockfanning** [comment] 2022-03-29 15:38
Re-opening because of reports that this is still an issue. @MoBosse can you link to an example of where the issue is still happening? I'm thinking that there may be another case of data that we didn't consider.

**Comment by MoBosse** [comment] 2022-03-30 05:44
@brockfanning 
[Here ](https://mobosse.github.io/sdg-indicators/2-4-1/) is an example where the issue occurs.
With corresponding data repository [here](https://github.com/MoBosse/sdg-data)

**Comment by brockfanning** [comment] 2022-03-30 17:28
@MoBosse Would you be able to test the PR at #1588? It is built from 1.8.0-dev so should otherwise be identical to 1.8.0-beta3. (If it works, I'm wondering if we could get it in for the 1.8.0 release.)

**Comment by LucyGwilliamAdmin** [comment] 2022-04-07 11:08
Closing as went in to 1.8.0. Fixed by #1588

**Closed by LucyGwilliamAdmin** 2022-04-07 11:08 UTC
Labels: bug
