### ISSUE TITLE
contrast toggle buttons get lost when using internet explorer

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#749] opened 2020-06-18 08:58 UTC
**Please complete the following information** 
Site repository URL: https://g205sdgs.github.io/sdg-indicators/
Open SDG version: 1.0.0

**Describe the bug**
contrast toggle buttons are not shown using internet explorer

**To Reproduce**

**Expected behavior**
Buttons should be visible as in other browsers

**Screenshots**
I.E.:
![grafik](https://user-images.githubusercontent.com/50657629/84999607-aeb84280-b151-11ea-93d0-016a2c9ce8f3.png)
Firefox:
![grafik](https://user-images.githubusercontent.com/50657629/84999654-bed02200-b151-11ea-9358-7773d86bbfa1.png)

**Desktop (please complete the following information):**
 - OS: Win7/Win10
 - Browser: Internet explorer
 - Version: 11

**Smartphone (please complete the following information):**

Works as expected with chrome and firefox

**Additional context**

**Comment by SavvasStephanides** [comment] 2020-06-18 12:20
@MoBosse Thank you Moritz. Good catch. I can confirm that it doesn't show up in IE11. I have also tested in the UK site and the demo starter site and they all have the same effect. The error in the console seems to be `'accessibilitySwitcher' is undefined`

**Comment by MoBosse** [comment] 2020-07-02 14:14
Just noticed that all data-related aspects of the indicator pages (chart, table, selection of sub-categories,...) do not get loaded when you open them in internet explorer. Here you get the same error message @SavvasStephanides mentioned about the `accessibilitySwitcher `and additionally the message that `indicatorModel `is undefined.
Tested on our [staging site](https://g205sdgs.github.io/sdg-indicators/1-2-1/) and the [UK site](https://sdgdata.gov.uk/1-1-1/).

**Comment by brockfanning** [comment] 2020-07-03 00:43
I think this should be fixed by #757.

**Closed** 2020-07-06 13:41 UTC
Labels: bug
