### ISSUE TITLE
Text disappears from chart area when clicked, in high contrast.

### ISSUE THREAD

**Issue by jwestw** [open-sdg/open-sdg#1134] opened 2021-03-05 10:08 UTC
**Please complete the following information** 
Site repository URL: https://github.com/ONSdigital/sdg-indicators/tree/1.3.0-beta1
Feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1.3.0-beta1/
Open SDG version: 1.3.0-beta

**Describe the bug**
The text below the chart, which includes text such as " Source", "Geographical Area" and "Unit of Measurement" disappears from chart area when clicked, in high contrast. What seems to be happening is that the text turns black when the chart area is clicked. So it becomes black on a black background, and hence disappears. 

**To Reproduce**
1. Go to any chart on the [1.3.0-beta1 feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1.3.0-beta1/), e.g. [this](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1.3.0-beta1/3-1-1/)
2. Click on the high contrast icon so the background goes black
3. Click on the chart area, so a yellow box appears around it
4. You should notice that the text disappears. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by LucyGwilliamAdmin** [comment] 2021-03-05 13:17
This is duplicate of #1124

**Comment by LucyGwilliamAdmin** [comment] 2021-06-23 13:41
Closing as this was fixed by #1137

**Closed** 2021-06-23 13:43 UTC
Labels: 1.3.0, bug
